/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author user
 */
public class ajouterVente extends javax.swing.JFrame {

    /**
     * Creates new form ajouterVente
     */
    public ajouterVente() {
    initComponents();
    

   btnajoutvente.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        String codeMedicament = inputlcodemedicament.getText();
        String quantiteVendueText = inputqtevendue.getText();

        if (codeMedicament.isEmpty() || quantiteVendueText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs !");
            return;
        }

        int quantiteVendue;
        try {
            quantiteVendue = Integer.parseInt(quantiteVendueText);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "La quantité vendue doit être un nombre entier !");
            return;
        }

        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacie", "root", "")) {
            String query = "SELECT quantite FROM medicament WHERE code_medic = ?";
            try (PreparedStatement statement = conn.prepareStatement(query)) {
                statement.setString(1, codeMedicament);
                ResultSet resultSet = statement.executeQuery();

                if (!resultSet.next()) {
                    JOptionPane.showMessageDialog(null, "Le code médicament n'existe pas !");
                    return;
                }

                int currentQuantity = resultSet.getInt("quantite");

                if (quantiteVendue > currentQuantity) {
                    JOptionPane.showMessageDialog(null, "La quantité vendue dépasse la quantité disponible !");
                    return;
                }

                if (currentQuantity >= quantiteVendue) {
                    int updatedQuantity = currentQuantity - quantiteVendue;
                    String updateQuery = "UPDATE medicament SET quantite = ? WHERE code_medic = ?";
                    try (PreparedStatement updateStatement = conn.prepareStatement(updateQuery)) {
                        updateStatement.setInt(1, updatedQuantity);
                        updateStatement.setString(2, codeMedicament);
                        updateStatement.executeUpdate();
                    }
                }

                String selectQuery = "SELECT quantite_vendue FROM vente WHERE code_medic = ?";
                try (PreparedStatement selectStatement = conn.prepareStatement(selectQuery)) {
                    selectStatement.setString(1, codeMedicament);
                    ResultSet selectResultSet = selectStatement.executeQuery();

                    if (selectResultSet.next()) {
                        int previousQuantity = selectResultSet.getInt("quantite_vendue");
                        quantiteVendue += previousQuantity;

                        String updateQuery = "UPDATE vente SET quantite_vendue = ? WHERE code_medic = ?";
                        try (PreparedStatement updateStatement = conn.prepareStatement(updateQuery)) {
                            updateStatement.setInt(1, quantiteVendue);
                            updateStatement.setString(2, codeMedicament);
                            updateStatement.executeUpdate();
                        }
                    } else {
                        String insertQuery = "INSERT INTO vente (code_medic, quantite_vendue) VALUES (?, ?)";
                        try (PreparedStatement insertStatement = conn.prepareStatement(insertQuery)) {
                            insertStatement.setString(1, codeMedicament);
                            insertStatement.setInt(2, quantiteVendue);
                            insertStatement.executeUpdate();
                        }
                    }
                }

                conn.close();
                JOptionPane.showMessageDialog(null, "Vente ajoutée avec succès !");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erreur lors de l'ajout de la vente !");
        }
    }
});
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnprec = new javax.swing.JLabel();
        btnaccueil = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputlcodemedicament = new javax.swing.JTextField();
        inputqtevendue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnajoutvente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PAGEREF.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 741, -1));

        btnprec.setBackground(new java.awt.Color(0, 204, 0));
        btnprec.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnprec.setForeground(new java.awt.Color(255, 255, 255));
        btnprec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnprec.setText("Page precedente");
        btnprec.setOpaque(true);
        btnprec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprecMouseClicked(evt);
            }
        });
        getContentPane().add(btnprec, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 148, 190, 28));

        btnaccueil.setBackground(new java.awt.Color(0, 204, 0));
        btnaccueil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnaccueil.setForeground(new java.awt.Color(255, 255, 255));
        btnaccueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnaccueil.setText("Page d'accueil");
        btnaccueil.setOpaque(true);
        btnaccueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaccueilMouseClicked(evt);
            }
        });
        getContentPane().add(btnaccueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 148, 190, 28));

        jLabel4.setBackground(new java.awt.Color(2, 153, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("code medicament");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 258, 180, 33));

        jLabel6.setBackground(new java.awt.Color(2, 153, 0));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("la Quantite vendue");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 303, 180, 33));

        inputlcodemedicament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputlcodemedicamentActionPerformed(evt);
            }
        });
        getContentPane().add(inputlcodemedicament, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 258, 180, 33));
        getContentPane().add(inputqtevendue, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 304, 180, 33));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("L'ajout d'une vente:");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 197, 238, -1));

        btnajoutvente.setBackground(new java.awt.Color(51, 170, 0));
        btnajoutvente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnajoutvente.setForeground(new java.awt.Color(255, 255, 255));
        btnajoutvente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajouter.png"))); // NOI18N
        btnajoutvente.setText("Ajouter Produit");
        btnajoutvente.setOpaque(true);
        btnajoutvente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnajoutventeMouseClicked(evt);
            }
        });
        btnajoutvente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajoutventeActionPerformed(evt);
            }
        });
        getContentPane().add(btnajoutvente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 395, 45));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputlcodemedicamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputlcodemedicamentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputlcodemedicamentActionPerformed

    private void btnajoutventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajoutventeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnajoutventeActionPerformed

    private void btnajoutventeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajoutventeMouseClicked
    
    }//GEN-LAST:event_btnajoutventeMouseClicked

    private void btnprecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprecMouseClicked
     gestionvente gestionvente = new gestionvente();
     gestionvente.setVisible(true);
     gestionvente.setLocationRelativeTo(null);
     this.dispose();
    }//GEN-LAST:event_btnprecMouseClicked

    private void btnaccueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccueilMouseClicked
        MainPage MainPage = new MainPage();
        MainPage.setVisible(true);
        MainPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnaccueilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouterVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouterVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouterVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouterVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ajouterVente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnaccueil;
    private javax.swing.JButton btnajoutvente;
    private javax.swing.JLabel btnprec;
    private javax.swing.JTextField inputlcodemedicament;
    private javax.swing.JTextField inputqtevendue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
