/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author user
 */
public class Gestionfournisseurs extends javax.swing.JFrame {

    /**
     * Creates new form gestiondesutilisateurs
     */
    public Gestionfournisseurs() {
        initComponents();
         afficherFournisseurs();
    }
    
    
    
    public void afficherFournisseurs() {
    DefaultTableModel model = (DefaultTableModel) tablefournisseur.getModel();
    model.setRowCount(0);

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacie", "root", "")) {
        String query = "SELECT code_fournisseur, prenom_fournisseur, nom_fournisseur, age_fournisseur, telephone_fournisseur, addresse_fournisseur FROM fournisseur";
        PreparedStatement statement = conn.prepareStatement(query);
        ResultSet resultSet = statement.executeQuery();

        while (resultSet.next()) {
            String codeFournisseur = resultSet.getString("code_fournisseur");
            String prenom = resultSet.getString("prenom_fournisseur");
            String nom = resultSet.getString("nom_fournisseur");
            int age = resultSet.getInt("age_fournisseur");
            String telephone = resultSet.getString("telephone_fournisseur");
            String adresse = resultSet.getString("addresse_fournisseur");

            model.addRow(new Object[]{codeFournisseur, prenom, nom, age, telephone, adresse});
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
}
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnprec = new javax.swing.JLabel();
        btnaccueil = new javax.swing.JLabel();
        ajoutfournisseur = new javax.swing.JButton();
        supprimerfournisseur = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablefournisseur = new javax.swing.JTable();
        chercherfournisseur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PAGEREF.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnprec.setBackground(new java.awt.Color(0, 204, 0));
        btnprec.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnprec.setForeground(new java.awt.Color(255, 255, 255));
        btnprec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnprec.setText("la page precedente");
        btnprec.setOpaque(true);
        btnprec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprecMouseClicked(evt);
            }
        });
        getContentPane().add(btnprec, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 30));

        btnaccueil.setBackground(new java.awt.Color(0, 204, 0));
        btnaccueil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnaccueil.setForeground(new java.awt.Color(255, 255, 255));
        btnaccueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnaccueil.setText("la page d'accueil");
        btnaccueil.setOpaque(true);
        btnaccueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaccueilMouseClicked(evt);
            }
        });
        getContentPane().add(btnaccueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 180, 30));

        ajoutfournisseur.setBackground(new java.awt.Color(51, 170, 0));
        ajoutfournisseur.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ajoutfournisseur.setForeground(new java.awt.Color(255, 255, 255));
        ajoutfournisseur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajouter.png"))); // NOI18N
        ajoutfournisseur.setText("Ajouter fournisseur");
        ajoutfournisseur.setOpaque(true);
        ajoutfournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutfournisseurMouseClicked(evt);
            }
        });
        ajoutfournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutfournisseurActionPerformed(evt);
            }
        });
        getContentPane().add(ajoutfournisseur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 230, 40));

        supprimerfournisseur.setBackground(new java.awt.Color(51, 170, 0));
        supprimerfournisseur.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        supprimerfournisseur.setForeground(new java.awt.Color(255, 255, 255));
        supprimerfournisseur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supprimer.png"))); // NOI18N
        supprimerfournisseur.setText("supprimer fournisseur");
        supprimerfournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerfournisseurMouseClicked(evt);
            }
        });
        supprimerfournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerfournisseurActionPerformed(evt);
            }
        });
        getContentPane().add(supprimerfournisseur, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 260, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("la gestion des fournisseurs");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        tablefournisseur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "numero fournisseur", "prenom", "nom", "age", "telephone", "adresse"
            }
        ));
        jScrollPane1.setViewportView(tablefournisseur);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 680, 209));

        chercherfournisseur.setBackground(new java.awt.Color(51, 170, 0));
        chercherfournisseur.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        chercherfournisseur.setForeground(new java.awt.Color(255, 255, 255));
        chercherfournisseur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chercher.png"))); // NOI18N
        chercherfournisseur.setText("chercher  fournisseur");
        chercherfournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chercherfournisseurMouseClicked(evt);
            }
        });
        getContentPane().add(chercherfournisseur, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 210, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprecMouseClicked
        MainPage MainPage = new MainPage();
        MainPage.setVisible(true);
        MainPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnprecMouseClicked

    private void btnaccueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccueilMouseClicked
        MainPage MainPage = new MainPage();
        MainPage.setVisible(true);
        MainPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnaccueilMouseClicked

    private void ajoutfournisseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutfournisseurMouseClicked
        ajouterfournisseur ajouterfournisseur = new ajouterfournisseur();
        ajouterfournisseur.setVisible(true);
        ajouterfournisseur.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ajoutfournisseurMouseClicked

    private void ajoutfournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutfournisseurActionPerformed

    }//GEN-LAST:event_ajoutfournisseurActionPerformed

    private void supprimerfournisseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerfournisseurMouseClicked
       supprimerfournisseur supprimerfournisseur = new supprimerfournisseur();
       supprimerfournisseur.setVisible(true);
       supprimerfournisseur.setLocationRelativeTo(null);
       this.dispose();       
    }//GEN-LAST:event_supprimerfournisseurMouseClicked

    private void supprimerfournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerfournisseurActionPerformed

    }//GEN-LAST:event_supprimerfournisseurActionPerformed

    private void chercherfournisseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chercherfournisseurMouseClicked
       recherchefournisseur recherchefournisseur = new recherchefournisseur();
       recherchefournisseur.setVisible(true);
       recherchefournisseur.setLocationRelativeTo(null);
       this.dispose(); 
    }//GEN-LAST:event_chercherfournisseurMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestionfournisseurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestionfournisseurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestionfournisseurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestionfournisseurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestionfournisseurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutfournisseur;
    private javax.swing.JLabel btnaccueil;
    private javax.swing.JLabel btnprec;
    private javax.swing.JButton chercherfournisseur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton supprimerfournisseur;
    private javax.swing.JTable tablefournisseur;
    // End of variables declaration//GEN-END:variables
}
