/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class gestionvente extends javax.swing.JFrame {

    /**
     * Creates new form gestionvente
     */
    public gestionvente() {
    initComponents();
    chargerDonneesVente();
}

    private void chargerDonneesVente() {
    DefaultTableModel model = (DefaultTableModel) tableventes.getModel();
    model.setRowCount(0); // Clear existing data

    String sql = "SELECT * FROM vente";

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacie", "root", "");
         PreparedStatement stmt = conn.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            Object[] row = new Object[3];
            row[0] = rs.getString("num_vente");
            row[1] = rs.getString("code_medic");
            row[2] = rs.getInt("quantite_vendue");
            model.addRow(row);
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ajoutvent = new javax.swing.JButton();
        annulevente = new javax.swing.JButton();
        modifvente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnprec = new javax.swing.JLabel();
        btnaccueil = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableventes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PAGEREF.jpg"))); // NOI18N

        ajoutvent.setBackground(new java.awt.Color(51, 170, 0));
        ajoutvent.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ajoutvent.setForeground(new java.awt.Color(255, 255, 255));
        ajoutvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajouter.png"))); // NOI18N
        ajoutvent.setText("Ajouter vente");
        ajoutvent.setOpaque(true);
        ajoutvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutventMouseClicked(evt);
            }
        });
        ajoutvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutventActionPerformed(evt);
            }
        });

        annulevente.setBackground(new java.awt.Color(51, 170, 0));
        annulevente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        annulevente.setForeground(new java.awt.Color(255, 255, 255));
        annulevente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supprimer.png"))); // NOI18N
        annulevente.setText("Annuler vente");
        annulevente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annuleventeMouseClicked(evt);
            }
        });
        annulevente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annuleventeActionPerformed(evt);
            }
        });

        modifvente.setBackground(new java.awt.Color(51, 170, 0));
        modifvente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        modifvente.setForeground(new java.awt.Color(255, 255, 255));
        modifvente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modifier.png"))); // NOI18N
        modifvente.setText("modifier vente");
        modifvente.setOpaque(true);
        modifvente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifventeMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("la gestion des ventes");

        btnprec.setBackground(new java.awt.Color(0, 204, 0));
        btnprec.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnprec.setForeground(new java.awt.Color(255, 255, 255));
        btnprec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnprec.setText("la page precedente");
        btnprec.setOpaque(true);
        btnprec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprecMouseClicked(evt);
            }
        });

        btnaccueil.setBackground(new java.awt.Color(0, 204, 0));
        btnaccueil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnaccueil.setForeground(new java.awt.Color(255, 255, 255));
        btnaccueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnaccueil.setText("la page d'accueil");
        btnaccueil.setOpaque(true);
        btnaccueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaccueilMouseClicked(evt);
            }
        });

        tableventes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "numero vente", "code medic", "la quantite"
            }
        ));
        jScrollPane1.setViewportView(tableventes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnprec, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnaccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modifvente, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(ajoutvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(annulevente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnprec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ajoutvent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(annulevente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(modifvente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajoutventActionPerformed

    private void annuleventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annuleventeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annuleventeActionPerformed

    private void btnprecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprecMouseClicked
       MainPage MainPage = new MainPage();
       MainPage.setVisible(true);
       MainPage.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_btnprecMouseClicked

    private void btnaccueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccueilMouseClicked
        MainPage MainPage = new MainPage();
       MainPage.setVisible(true);
       MainPage.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_btnaccueilMouseClicked

    private void ajoutventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutventMouseClicked
       ajouterVente ajouterVente = new ajouterVente();
       ajouterVente.setVisible(true);
       ajouterVente.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_ajoutventMouseClicked

    private void annuleventeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annuleventeMouseClicked
         AnnulerVente AnnulerVente = new AnnulerVente();
       AnnulerVente.setVisible(true);
       AnnulerVente.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_annuleventeMouseClicked

    private void modifventeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifventeMouseClicked
       modifierVente modifierVente = new modifierVente();
       modifierVente.setVisible(true);
       modifierVente.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_modifventeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionvente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionvente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionvente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionvente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionvente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutvent;
    private javax.swing.JButton annulevente;
    private javax.swing.JLabel btnaccueil;
    private javax.swing.JLabel btnprec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifvente;
    private javax.swing.JTable tableventes;
    // End of variables declaration//GEN-END:variables
}
