/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class supprimermedicament1 extends javax.swing.JFrame {

    /**
     * Creates new form supprimermedicament1
     */
    public supprimermedicament1() {
        initComponents();
    }
    private boolean supprimerMedicament(int codeMedicament) {
    try {
        // Établir une connexion à la base de données
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/pharmacie", "root", "");
        
        // Préparer la requête SQL pour supprimer le médicament
        String sql = "DELETE FROM medicament WHERE code_medic = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        
        stmt.setInt(1, codeMedicament);
        

        int rowsAffected = stmt.executeUpdate();
        
        stmt.close();
        conn.close();
        
        return rowsAffected > 0;
    } catch (SQLException e) {
        e.printStackTrace();
        return false;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputsupprimermed = new javax.swing.JTextField();
        btnsupprimermed = new javax.swing.JButton();
        btnprec = new javax.swing.JButton();
        btnaccueil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PAGEREF.jpg"))); // NOI18N

        inputsupprimermed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputsupprimermedActionPerformed(evt);
            }
        });

        btnsupprimermed.setBackground(new java.awt.Color(51, 170, 0));
        btnsupprimermed.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnsupprimermed.setForeground(new java.awt.Color(255, 255, 255));
        btnsupprimermed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supprimer.png"))); // NOI18N
        btnsupprimermed.setText("Supprimer medicament");
        btnsupprimermed.setBorderPainted(false);
        btnsupprimermed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprimermedActionPerformed(evt);
            }
        });

        btnprec.setBackground(new java.awt.Color(0, 204, 0));
        btnprec.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnprec.setForeground(new java.awt.Color(255, 255, 255));
        btnprec.setText("Page précedente");
        btnprec.setBorderPainted(false);
        btnprec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprecMouseClicked(evt);
            }
        });
        btnprec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprecActionPerformed(evt);
            }
        });
        btnprec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnprecKeyReleased(evt);
            }
        });

        btnaccueil.setBackground(new java.awt.Color(0, 204, 0));
        btnaccueil.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnaccueil.setForeground(new java.awt.Color(255, 255, 255));
        btnaccueil.setText("Page d'acceuil");
        btnaccueil.setBorderPainted(false);
        btnaccueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaccueilMouseClicked(evt);
            }
        });
        btnaccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccueilActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel2.setText("Saisir code medicament :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnprec, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(btnaccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(inputsupprimermed, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnsupprimermed, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprec, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputsupprimermed, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnsupprimermed, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputsupprimermedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputsupprimermedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputsupprimermedActionPerformed

    private void btnsupprimermedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprimermedActionPerformed

        String codeMedicamentStr = inputsupprimermed.getText();

    if (codeMedicamentStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Veuillez saisir un code de médicament.", "Erreur", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int codeMedicament = Integer.parseInt(codeMedicamentStr);
        boolean suppressionReussie = supprimerMedicament(codeMedicament);

        if (suppressionReussie) {
            JOptionPane.showMessageDialog(this, "Le médicament a été supprimé avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Le médicament que vous voulez supprimer n'existe pas.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Veuillez saisir un code de médicament valide.", "Erreur", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnsupprimermedActionPerformed

    private void btnprecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprecMouseClicked
       gestionstock1 gestionstock1 = new gestionstock1();
       gestionstock1.setVisible(true);
       gestionstock1.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_btnprecMouseClicked

    private void btnprecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprecActionPerformed

    private void btnaccueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccueilMouseClicked
        MainPage MainPage = new MainPage();
       MainPage.setVisible(true);
       MainPage.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_btnaccueilMouseClicked

    private void btnaccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccueilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaccueilActionPerformed

    private void btnprecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnprecKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprecKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supprimermedicament1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supprimermedicament1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supprimermedicament1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supprimermedicament1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new supprimermedicament1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaccueil;
    private javax.swing.JButton btnprec;
    private javax.swing.JButton btnsupprimermed;
    private javax.swing.JTextField inputsupprimermed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
